mainSections   = ["post"]
rssFullContent = true
favicon        = "img/avatar.png"

[footer]
    since = 2020

[sidebar]
    emoji    = "✏️"
    subtitle = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."
    avatar   = "img/avatar.png"

[article]
    [article.license]
        enabled = true
        default = "Licensed under CC BY-NC-SA 4.0"

[widgets]
    homepage = [
        { type = "search" },
        { type = "archives", params = { limit = 5 } },
        { type = "categories", params = { limit = 10 } },
        { type = "tag-cloud", params = { limit = 10 } },
    ]
    page     = [{ type = "toc" }]

[comments]
    enabled = true
    provider = "giscus"

[comments.giscus]
    repo = "kaipi65/benjiem-blog"
    repoId = "R_kgDORV8ryQ"
    category = "Announcements"
    categoryId = "DIC_kwDORV8ryc4C2-qC"
    mapping = "title"
    lightTheme = "light"
    darkTheme = "transparent_dark"